### ISSUE TITLE
Multilevel Sensor "Water flow" (0x38) is not supported

### ISSUE THREAD

**Issue by octopussy1** [Z-Wave-Me/z-way-issues#152] opened 2019-03-11 09:24 UTC
The Multilevel Sensor "Water flow" (0x38) is not supported. Would be really good if this could be implemented for the next release as we do need this for our device.

**Comment by PoltoS** [comment] 2019-03-29 06:36
Duplicate of #150

**Closed as completed** 2019-03-29 06:36 UTC
