### ISSUE TITLE
MakeIndex.py

### ISSUE THREAD

**Issue by rsebes** [Z-Wave-Me/z-way-issues#38] opened 2015-02-20 21:17 UTC
I've discovered not all devices are showing up in the ZDDX device database index. When the index is ran, there are errors that state:
Error loading Z-Wave Device Description XML 584-014f4774-3032-03-03-67-00-15.xml: list index out of range.
(I know it has been stated that this is a normal error but more may be going on with this) 

This specific device does not show up in the list when trying to select the device description in the expert UI. here's this device in the pepper1 database: http://www.pepper1.net/zwavedb/device/584. The xml shows up in the /opt/z-way-server/ZDDX/ directory (584-014f-4774-30-32-03-03-67-00-15.xml) This is the same for 5 other devices. 26 unnamed devices are in the device description dropdown and 31 devices get the index out of range error in MakeIndex.py. If this error isn't a big deal and they get created in the index, anyway shouldn't there be 31 unnamed devices in the device description dropdown?
![image](https://cloud.githubusercontent.com/assets/11092410/6309481/7aece30c-b913-11e4-89f5-09d1539089ac.png)
![image](https://cloud.githubusercontent.com/assets/11092410/6309491/979d8ba0-b913-11e4-8b83-4024801131cd.png)

**Comment by pieceofsummer** [comment] 2015-02-21 19:22
Have not looked through all the files, but 584-014f-4774-30-32-03-03-67-00-15.xml has no specific class present. I believe this should be fixed on Pepper One side.

**Comment by rsebes** [comment] 2015-02-23 14:01
I wonder if adding additional logic to the code to give more meaningful error messages could be possible so it's easier for some of us more "green" members to identify issues with the pepper1 db and those that may create their own device xml. 

Also, what is the process for getting corrections made to the pepper1 database?

**Comment by pieceofsummer** [comment] 2015-02-23 14:47
There's an xsd schema to get meaningful error messages. I don't know why it is not validated automatically on pepper1 side when uploading the xml, but at least an uploader should do it on his side. 
MakeIndex.py is not a debugging tool here, it expects the db to be valid.

**Comment by pz1** [comment] 2015-03-29 14:18
Pepper1 does not provide a valid schema reference in the header. So it is impossible to validate these files with online validators (e.g. http://validator.w3.org), or local tools (e.g. Altova XML-Spy). I have tried both to no avail. I also asked Pepper1 before to make a proper schema linkage in the header.

**Comment by PoltoS** [comment] 2015-03-29 15:33
The schema is in the same folder, you can validate these files to see all problems.

From time to time we are validating them, but all remaining are just incomplete data, so they should be either deleted, or we need to find people having these devices to get full data.

**Comment by pz1** [comment] 2015-03-29 18:42
Imho life would be easier and better if Pepper1 extended their XML header information to also include a single schema instance location from their site, to ensure data integrity over time.
(I was able to validate with the schema.xsd from folder ZDDX)

**Comment by PoltoS** [comment] 2015-03-29 20:20
Sure, but they have no time and motivation right now to do it. Just don't care about 15 of 500 files

**Comment by Mirarkitty** [comment] 2015-05-21 14:01
Most of those seems to bork on not having a specificClass. It seems like a small problem to fix. And it's not 15, it's 33. Is it possible for the indexer to default the specificClass if it doesn't exist?

**Comment by PoltoS** [comment] 2015-05-21 16:50
no, it is not possible. these records are to be filled  correctly or deleted

**Comment by PoltoS** [comment] 2016-02-22 10:06
Clnot a bug. Requires someo e to re-test all these devices and help us fill corresponding fields.

**Closed as completed** 2016-02-22 10:06 UTC
