### ISSUE TITLE
Multilevel Sensor Types "Water Chlorine level", "Water acidity", "Water Oxidation" are not supported 

### ISSUE THREAD

**Issue by octopussy1** [Z-Wave-Me/z-way-issues#153] opened 2019-03-11 09:28 UTC
Multilevel Sensor Types "Water Chlorine level" (0x42), "Water acidity" (0x43), "Water Oxidation" (0x44) are not supported.

**Comment by PoltoS** [comment] 2019-03-29 06:38
Duplicate of #150

**Closed as completed by PoltoS** 2019-03-29 06:38 UTC
