### ISSUE TITLE
Notification Water Alarm doesn't detect "Water flow alarm" event (0x06)

### ISSUE THREAD

**Issue by octopussy1** [Z-Wave-Me/z-way-issues#151] opened 2019-03-11 09:21 UTC
Notification Water Alarm doesn't detect "Water flow alarm" event (0x06). Leak detection (0x01) does work. Have not tested the other Water Alarm event types )e.g. "Water temperature alarm" (x08).

**Comment by PoltoS** [comment] 2019-03-29 06:35
Duplicate of #150

**Closed as completed by PoltoS** 2019-03-29 06:35 UTC
